# Generated by Django 3.2.5 on 2021-07-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210715_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statu',
            new_name='Status',
        ),
    ]
