# Generated by Django 3.2.5 on 2021-07-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_statu_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board_id',
        ),
        migrations.RemoveField(
            model_name='status',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
    ]
